### ISSUE TITLE
[Sentinel] Fix issues with active-contract endpoint

### ISSUE THREAD

**Issue by 0xean** [arkeonetwork/arkeo#113]
#### Background
Currently the active contract endpoint just iterates the mem store to find a match for an active contract, this could be greatly improved to index contracts by spender. A spender could have multiple contracts in varying states in the mem store, so we would need to handle that accordingly. 

Finally, if we cannot find an active contract, we should call arkeo itself to see if there is one we missed in our cache. 

#### Acceptance Criteria
1. fix mem store cache to a more efficient lookup for a user's active contracts
2. add functionality to find the active contract for a specific spender, provider, and chain
3. add fallback for a cache miss to hit the arkeo node as a last resort.
4. extend and clean up tests for these scenarios

**Comment by cbarraford** [comment]
sentinel shouldn't be considered an API endpoint to be queried for general purposes. It should only maintain its own "active contracts" where this provider is the provider.

If you're looking for general information, query the directory service or a full node.
