### ISSUE TITLE
Register invariants to halt chain 

### ISSUE THREAD

**Issue by 0xean** [arkeonetwork/arkeo#119]
#### Background
The cosmos sdk offers the crisis module to register invariant states that should halt the chain 

https://docs.cosmos.network/main/modules/crisis

We should draft all invariant states based and implement this fail safe mechanism

#### AC
1. draft list of all invariant states that may exist for arkeo 
2. implement crisis module with tests

**Comment by cbarraford** [comment]
invariants that I can think of

* module contains enough funds to pay out the remainder of all contracts. This is computationally expensive (unless we A) delete expired contracts when done, or B) maintain an index of "live" contracts in the kvstore)

**Comment by 0xean** [comment]
- total supply of uarkeo 121 MM is never violated
- checking that bond module token balance is > total bond expected globally
- consider removing them in the future or at a certain block we bypass if these are computationally expensive. 
- consider pruning KV stores to improve this process for both providers and contracts.
