### ISSUE TITLE
http configs to prevent dos

### ISSUE THREAD

**Issue by cbarraford** [arkeonetwork/arkeo#263]
secure sentinel see the timeouts/limits section: https://bruinsslot.jp/post/go-secure-webserver/

```golang
import socket
import time

HOST = "localhost"
PORT = 3636

sockets = []
for i in range(1000000):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((HOST, PORT))
    s.send(b"GET /metadata.json HTTP/1.1\r\n")
    s.send(b"x"*1024*1024)
    sockets.append(s)
```

**Comment by InnovationTheory** [comment]
- Enhanced the security of the Sentinel HTTP server by implementing various measures, including:
-- Setting appropriate timeouts
-- Limiting request sizes to prevent DoS attacks
-- Ensuring secure communication using TLS and secure cipher suites
- Changes Made:
-- Configured timeouts and limits
-- Added ReadTimeout
