### ISSUE TITLE
event ordering

### ISSUE THREAD

**Issue by cbarraford** [arkeonetwork/arkeo#266]
this one i never fully investigated, but the worry was that by doing separate subscribes, it might be possible for events to be processed in the wrong order, which could lead to weirdness. from my old notes on sentinel, the one thing i wanted to check is https://github.com/arkeonetwork/arkeo/blob/master/sentinel/event_stream.go#L49
whether the ordering of events is ensured here

**Comment by InnovationTheory** [comment]
- Implemented a unified channel that acts as a queue to hold events subscribed based on defined queries.
- Added events to the event queue based on queries, which can then be processed via dispatch.
- Handled events in dispatch based on queries for processing.
- Ensured events are processed in the order they are received.
- Enabled the event listener to handle events in the order they are received.
