### ISSUE TITLE
Phase 1 internal testing

### ISSUE THREAD

**Issue by 0xean** [arkeonetwork/arkeo#59]
#### Background

Currently internal testers have been working against this document 
https://www.notion.so/Round-1-Stagenet-Testing-Docs-8f459efa5281429780044efb57130598
There are a variety of different issues that have been encountered in getting through the entire test suite.

For phase 1 to be considered done we should meet the below AC

#### Acceptance Criteria
- above notion doc is updated to include the needed steps from a clean environment with no dependencies installed to completion of all tests steps.  We may want to document some of setup steps elsewhere, perhaps in the README.md since they may be used for other development purposes. 
- All bug fixes needed to complete the outlined steps on the Arkeo chain itself have been completed. 
- Verified by one other developer that they can take a fresh ec2 instance from nothing to completing all steps. 

#### Other notes
We are spinning up a new seed node to test against in the cloud. @asamere can fill in details to access it once complete.

**Comment by asamere** [comment]
we might be able to simplify setup significantly (removing the need to further document) by publishing binaries. we'll need full setup documentation for node operators, but these initial rounds of testing can likely get by without.

**Comment by LeonoorsCryptoman** [comment]
> we might be able to simplify setup significantly (removing the need to further document) by publishing binaries. we'll need full setup documentation for node operators, but these initial rounds of testing can likely get by without.

It is easier indeed, but not common practice (unless you have things developed which you don't want to have published yet). The majority of node operators in the Cosmos ecosystem prefer to being able to build the binaries themselves.

**Comment by jonisjongithub** [comment]
Yea, the goal should be a binary that can be downloaded and run, but of course that the source is open for those who want to compile and build their own binaries.

**Comment by LeonoorsCryptoman** [comment]
Perfect!

I saw you uploaded a gentx for a seed node, let me know when you need more validator nodes on the testnet :)

**Comment by 0xean** [comment]
I was able to open and close contracts today against the new node.  Unable to query data, but that is because of sentry.  Once stood up, I can retest again.  We may be very close to moving past this stage finally.

**Comment by nodeiistt** [comment]
Good Luck!
