### ISSUE TITLE
Allow pay as you go contract's to be cancelled if the provider has unbounded. 

### ISSUE THREAD

**Issue by 0xean** [arkeonetwork/arkeo#90]
#### Background
Currently we allow a provider to un-bond at any time regardless of the number of open contracts that may exist.  Subscription type contracts can cancel at any time, so this is fine for them, but a PayAsYouGo contract is not able to cancelled until it runs it course.

We should change this in the case that the provider has unbonded. 

#### AC
1. Allow a PayAsYouGo contract to be closed in the provider has unbonded
2. Add tests to ensure this scenario works and doesn't work still when the provider is bonded.

**Comment by johnnyluo** [comment]
Providers can unbond at anytime, but in this issue, I think we should only allow PayAsYouGo contract to cancel , when provider is unbond 100%
