### ISSUE TITLE
Allow provider to opt out of pay as you go or subscriptions

### ISSUE THREAD

**Issue by 0xean** [arkeonetwork/arkeo#91]
#### Background 
Currently a provider has no easy way of not providing one of the contract types.  They could set arbitrarily high prices but there should be an easy way for a provider to not support all the contract types. 

#### AC
1. Create boolean flag for the provider to be able to designate their support of PayAsYouGo and Subscription contract types
2. Add tests to ensure that contracts cannot be open against these providers when the flags are false.

**Comment by cbarraford** [comment]
i think the ability to specify multiple coins to be pain in, allows the ability. No need to do this issue anymore.
